# See: https://learn.microsoft.com/en-us/azure/aks/azure-csi-files-storage-provision#dynamically-provision-a-volume
# See: https://learn.microsoft.com/en-us/troubleshoot/azure/azure-kubernetes/mountoptions-settings-azure-files
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-file-dags
  namespace: airflow
  labels:
    volume: azure-file-dags
provisioner: file.csi.azure.com
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
  - cache=none
parameters:
  skuName: Standard_LRS
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-file-logs
  namespace: airflow
  labels:
    volume: azure-file-logs
provisioner: file.csi.azure.com
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
  - cache=none
parameters:
  skuName: Standard_LRS