apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-claim-dags
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azure-file-dags
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-claim-logs
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azure-file-logs
  resources:
    requests:
      storage: 5Gi