# TODO: https://kubernetes.io/docs/reference/access-authn-authz/rbac/
# apiVersion: v1
# kind: ServiceAccount
# metadata:
  # name: airflow-rbac
  # namespace: airflow
# ---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: airflow-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: airflow-keyvault
  namespace: airflow
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: "" # indicates the core API group
  # apiGroup: rbac.authorization.k8s.io