apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvault-sync
  namespace: airflow
spec:
  provider: azure                             
  secretObjects:                              # [OPTIONAL] SecretObjects defines the desired state of synced Kubernetes secret objects
  - data:
    - key: airflow-fernet-key                           # data field to populate
      objectName: airflow-fernet-key                        # name of the mounted content to sync; this could be the object name or the object alias
    - key: airflow-sql-database                        # data field to populate
      objectName: airflow-sql-database    
    - key: airflow-webserver-secret-key                        # data field to populate
      objectName: airflow-webserver-secret-key         
    - key: airflow-broker-url                      # data field to populate
      objectName: airflow-broker-url    
    - key: airflow-celery-result-backend
      objectName: airflow-celery-result-backend
    secretName: aks-airflow-secret                     # name of the Kubernetes secret object
    type: Opaque   
  parameters:
    usePodIdentity: "false"       
    clientID: "${USER_ASSIGNED_CLIENT_ID}" # Setting this to use workload identity
    keyvaultName: aks-airflow-key-0024     # Set to the name of your key vault
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects: |
      array:
        - |
          objectName: airflow-fernet-key
          objectType: secret
        - |
          objectName: airflow-sql-database
          objectType: secret
        - |
          objectName: airflow-webserver-secret-key
          objectType: secret
        - |
          objectName: airflow-broker-url
          objectType: secret
        - |
          objectName: airflow-celery-result-backend
          objectType: secret
    tenantId: 3196a18d-1c35-498a-b779-a082d45d2ab5